### ISSUE TITLE
\n in a field value breaks the FluxCsvParser

### ISSUE THREAD

**Issue by gmoigneu** [influxdata/influxdb-client-php#100]
__Steps to reproduce:__

1. Inject "\n" in a field
2. Query that field (stream, raw or query have the same behavior)

__Expected behavior:__

The response should escape weird characters in a field and not detect them as end of line.

__Actual behavior:__

The parser detects "\n" as end of line:

```
            // Break when a new line is found
            if ($byte === "\n") {
                break;
            }
```

We end up with a row that has less array values than the headers. Triggering an exception on `parseRecord()`:

```
$strVal = $csv[$fluxColumn->index + 1];
```

__Specifications:__

 - Client Version: 50738a76b770e8403cca3bcb38fef1aa210d1de4
 - InfluxDB Version: Influx Cloud as of Nov. 3rd

**Comment by bednar** [comment]
Hi @gmoigneu,

thanks for using our client.

I've prepared PR #101. If you would like to use dev version of client then install client via:

```console
composer require influxdata/influxdb-client-php:fix/response-with-new-line
```

- https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository

Regards

**Comment by gmoigneu** [comment]
Oh that's amazing @bednar ! Thank you so much for this. I confirm it works flawlessly.

I got it to work with a regex to circumvent the issue:

```
|> map(fn: (r) => ({
  r with
     payload: strings.replaceAll(v: r.payload, t: "\r\n", u: "return")
  })
)
```
