### ISSUE TITLE
How to use when project needs guzzlehttp/psr7": "^1.8.3 || ^2.1

### ISSUE THREAD

**Issue by supine-win** [influxdata/influxdb-client-php#104]
One package need guzzlehttp/psr7": "^1.8.3 || ^2.1, then install client , will get an error about conflict

**Comment by bednar** [comment]
Hi @supine-win,

thanks for using our client.

The client supports the `1.8.3` version of `guzzlehttp/psr7`. 

Can you share the output of `composer show -i`?  Did you try `composer update`?

I've also prepare PR #105 with support for `"guzzlehttp/psr7": "^1.7|^2.0.0"` . If you would like to use dev version of client then install client with following branch `psr7-latest`.


Regards
