### ISSUE TITLE
Transform FluxTable[] to array used in the front table

### ISSUE THREAD

**Issue by supine-win** [influxdata/influxdb-client-php#106]
Just as the title says

**Comment by bednar** [comment]
Hi @supine-win,

If you would like to have only one table in result then use the [`group()` function](https://docs.influxdata.com/flux/v0.x/stdlib/universe/group/) in your Flux query. You can also merge records from tables into `array` by:

```php
$tables = $this->queryApi->query('from(bucket:"my-bucket") |> range(start: 0) |> last()');

$records = array_merge(...array_map(function ($table): array {
    return $table->records;
}, $tables));

$values = array_map(function ($record): array {
    return $record->values;
}, $records);

print_r($values);
```

Regards

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
