### ISSUE TITLE
php v7.1 problem

### ISSUE THREAD

**Issue by S474N** [influxdata/influxdb-client-php#112]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Use Dockerfile to build
2. there is error in build process:

![image](https://user-images.githubusercontent.com/16512337/150513819-df81dac7-1b33-4cc7-b7c6-5ddc1114b0be.png)

__Expected behavior:__
Make cointainer 

__Actual behavior:__
Problem with building cointainer. If changed version in Dockerfile to 7.2, there isn't problem.

__Specifications:__
 - Platform: Docker Compose version v2.2.3

**Comment by bednar** [comment]
Hi @S474N,

thanks for using our client. 

I have prepared a fixed version within #114.

Regards

**Comment by bednar** [comment]
Hi @S474N,

I've prepared PR #114. If you would like to use a dev version of client then install client via:

```console
composer require influxdata/influxdb-client-php:master
```

- https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository

Regards
