### ISSUE TITLE
Switch Guzzle dependency to version 7 to prevent deprecation notices thrown in PHP 8.1

### ISSUE THREAD

**Issue by cstuder** [influxdata/influxdb-client-php#113]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Run any method which uses HTTP with PHP 8.1 and notices enabled

__Expected behavior:__
No notices being thrown, silent execution.

__Actual behavior:__
Notice thrown:

```text
Deprecated: http_build_query(): Passing null to parameter #2 ($numeric_prefix) of type string is deprecated in /.../vendor/guzzlehttp/guzzle/src/Client.php on line 445
```

__Notes__

PHP 8.1 has tightened parameter types. Guzzle version 6 is affected and according to [their issues](https://github.com/guzzle/guzzle/pull/2918) will not fix this deprecation notice, because Guzzle version 7 is the only supported one.

 `influxdata/influxdb-client-php` allows for both version in the `composer.json` requirements:

```json
"guzzlehttp/guzzle": "^6.2|^7.0.1",
```

This should be fixed to version 7 only.

__Specifications:__
 - Client Version: 2.5.0
 - InfluxDB Version: 2.1.1
 - Platform: PHP 8.1 on MacOS 12.1

**Comment by cstuder** [comment]
Maybe changing the dependency string alone is sufficient, but I wasn't able to run the tests on my machine for the moment. The `Dockerfile` would have to be changed to PHP8.1 as well, at least for running the tests.

**Comment by bednar** [comment]
Hi @cstuder,

thanks for using our client.

I will prepare PR to change a supported version of PHP to `7.2`. Meanwhile you can install your preferred version of `guzzle` by:

```
composer require guzzlehttp/guzzle:^7.0.1 guzzlehttp/psr7:^1.7
```

> The Dockerfile would have to be changed to PHP8.1 as well, at least for running the tests.

We want to use minimal supported version of PHP as a base for tests. The other version of PHP are tested in CI: https://app.circleci.com/pipelines/github/influxdata/influxdb-client-php

Regards

**Comment by bednar** [comment]
Hi @cstuder,

I've prepared PR #114. If you would like to use a dev version of client then install client via:

```console
composer require influxdata/influxdb-client-php:master
```

- https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository

Regards
