### ISSUE TITLE
Depend on PSR-18 instead of Guzzle.

### ISSUE THREAD

**Issue by tarjei** [influxdata/influxdb-client-php#120]
__Proposal:__
When working on projects that use many different external APIs, depending on a concrete version of one http library can become a problem. It would help a lot if `influx-client-php` could depend on [PSR-18](https://www.php-fig.org/psr/psr-18/) instead so that the concrete version of the library could vary more.

__Current behavior:__
Today the library depends on a given Guzzle version.

__Desired behavior:__
The guzzle dependencies switched to depending on http/common instead. See [Mailguns PHP lib](https://github.com/mailgun/mailgun-php/blob/master/composer.json) for an example.

__Use case:__
When working on projects that use many different external APIs, depending on a concrete version of one http library can become a problem. We are still running Guzzle 6.x and may have to do busywork just to use influxdb-client-php.

**Comment by bednar** [comment]
Hi @tarjei,

thanks for using our client.

Is this something you might be willing to help with?

Regards

**Comment by tarjei** [comment]
@bednar  I'm sorry, but not at the moment no :)

**Comment by bednar** [comment]
Hi @tarjei, 

We are preparing a new major version of the client (`v3.0.0`) which add supports for custom HTTP clients. Please try the preview version by:

```console
composer require influxdata/influxdb-client-php:generic-http-client
```

For more info about new major version see:

- https://github.com/influxdata/influxdb-client-php/pull/129
- https://github.com/influxdata/influxdb-client-php/blob/generic-http-client/CHANGELOG.md#300-unreleased
- https://github.com/influxdata/influxdb-client-php/blob/generic-http-client/README.md#custom-http-client

Regards
