### ISSUE TITLE
Can't use GuzzleHttp\Client 6.5.8 with influxdata/influxdb-client-php 3.4.0

### ISSUE THREAD

**Issue by fredmef** [influxdata/influxdb-client-php#151]
Hello,

I want to use Guzzle Http Client (guzzlehttp/guzzle: 6.5.8) with Influxdb Client 3.4.0 so I've done the followings:

1. `composer require influxdata/influxdb-client-php guzzlehttp/guzzle` 
2. and create a client with:
```php
$client = new InfluxDB2\Client([
    "url" => "http://localhost:8086",
    "token" => "my-token",
    "bucket" => "my-bucket",
    "org" => "my-org",
    "precision" => InfluxDB2\Model\WritePrecision::NS
]);
```
But when I connect this client I've the following error:
```bash
[23-Nov-2023 16:42:06 UTC] PHP Fatal error:  Uncaught TypeError: InfluxDB2\DefaultApi::configuredClient(): Argument #1 ($client) must be of type Psr\Http\Client\ClientInterface, GuzzleHttp\Client given, called in /var/www/html/vendor/influxdata/influxdb-client-php/src/InfluxDB2/DefaultApi.php on line 64 and defined in /var/www/html/vendor/influxdata/influxdb-client-php/src/InfluxDB2/DefaultApi.php:93
```

Can you explain me what I'm doing wrong ?

Regards.

**Comment by bednar** [comment]
Hi @fredmef,

Thank you for using our client.

Our client requires a PSR-18 HTTP client implementation. According to the [Guzzle changelog](https://github.com/guzzle/guzzle/blob/7.8/CHANGELOG.md#700-beta1---2019-12-30), support for PSR-18 starts from version 7.0.0. Could you please try updating your Guzzle library to a version at or above 7.0.0?

Best regards

**Comment by bednar** [comment]
The InfluxDB client is able to run with any implementation of PSR-18 compliant HTTP client - https://packagist.org/providers/psr/http-client-implementation. You can use different HTTP client which is compatible with your Drupal.

For more info see https://github.com/influxdata/influxdb-client-php#custom-http-client
