### ISSUE TITLE
Wrong timestamp value when query data

### ISSUE THREAD

**Issue by quangcanh2975** [influxdata/influxdb-client-php#153]
__Steps to reproduce:__
I found an issue when adding data with milliseconds:

1. Create a new bucket name `test` and add data by line protocols below:
```
data,id=1 value=1.0 1641340800504
data,id=1 value=2.0 1641340800710
```
3. Use influxdb-client-php to query data:
```
from(bucket: "test")
|> range(start: -3y)
```
```
{
    "columns": [
        {
            "index": 0,
            "label": "result",
            "dataType": "string",
            "group": false,
            "defaultValue": "_result"
        },
        {
            "index": 1,
            "label": "table",
            "dataType": "long",
            "group": false,
            "defaultValue": ""
        },
        {
            "index": 2,
            "label": "_start",
            "dataType": "dateTime:RFC3339",
            "group": true,
            "defaultValue": ""
        },
        {
            "index": 3,
            "label": "_stop",
            "dataType": "dateTime:RFC3339",
            "group": true,
            "defaultValue": ""
        },
        {
            "index": 4,
            "label": "_time",
            "dataType": "dateTime:RFC3339",
            "group": false,
            "defaultValue": ""
        },
        {
            "index": 5,
            "label": "_value",
            "dataType": "double",
            "group": false,
            "defaultValue": ""
        },
        {
            "index": 6,
            "label": "_field",
            "dataType": "string",
            "group": true,
            "defaultValue": ""
        },
        {
            "index": 7,
            "label": "_measurement",
            "dataType": "string",
            "group": true,
            "defaultValue": ""
        },
        {
            "index": 8,
            "label": "id",
            "dataType": "string",
            "group": true,
            "defaultValue": ""
        }
    ],
    "records": [
        {
            "table": 0,
            "values": {
                "result": "_result",
                "table": 0,
                "_start": "2011-01-31T01:41:09.625431Z",
                "_stop": "2024-02-01T07:41:09.625431Z",
                "_time": "2022-01-05T00:00:00.504Z",
                "_value": 1,
                "_field": "value",
                "_measurement": "data",
                "id": "1"
            }
        },
        {
            "table": 0,
            "values": {
                "result": "_result",
                "table": 0,
                "_start": "2011-01-31T01:41:09.625431Z",
                "_stop": "2024-02-01T07:41:09.625431Z",
                "_time": "2022-01-05T00:00:00.71Z",
                "_value": 2,
                "_field": "value",
                "_measurement": "data",
                "id": "1"
            }
        }
    ]
}
```
5. The second value's time is wrong, but it works fine when I query data in built-in Data Explorer, 
<img width="1239" alt="Screenshot 2024-01-31 at 14 45 15" src="https://github.com/influxdata/influxdb-client-php/assets/26849248/be3fd0f2-7fa1-4712-b27f-c2b356e3df53">

Can we have a way to avoid this issue?

__Expected behavior:__
"2022-01-05T00:00:00.710Z",

__Actual behavior:__
"_time": "2022-01-05T00:00:00.71Z" 

__Specifications:__
 - Client Version: 2.1
 - InfluxDB Version: 2.7.3
 - Platform: MacOS/Ubuntu

**Comment by bednar** [comment]
Hi @quangcanh2975,

Thank you for using our client, and for bringing your observation to our attention.

I've reviewed the details you provided regarding the expected and actual behavior of timestamps:

Expected: "2022-01-05T00:00:00.710Z"
Actual: "_time": "2022-01-05T00:00:00.71Z"
From a technical standpoint, this difference appears to be a matter of formatting, specifically the omission of trailing zeros in the timestamp. This is a common practice in many systems to streamline data representation without losing precision or altering the actual value.

Could you please clarify if this formatting discrepancy is causing specific issues in your application? For example, are you encountering problems with parsing this timestamp format, or is it affecting data processing in some way? Understanding the exact nature of any challenges you're facing will help us provide more targeted support or consider adjustments in future updates.

Looking forward to your response, and we're here to assist with any further questions or concerns you might have.

Best Regards
