### ISSUE TITLE
Composer error

### ISSUE THREAD

**Issue by chenphp** [influxdata/influxdb-client-php#154]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. I runed this command: composer require influxdata/influxdb-client-php guzzlehttp/guzzle
2. I got this 
![图片](https://github.com/influxdata/influxdb-client-php/assets/9495197/3b2eece5-3600-4f62-93ed-03433b8e182a)

__Expected behavior:__
Please help

__Actual behavior:__
Describe What actually happened.

__Specifications:__
 - Client Version:
 - InfluxDB Version:
 - Platform:

**Comment by bednar** [comment]
Hi @chenphp,

Thank you for using our client and reaching out for support.

Could you please share with us which version of Composer you are currently using? It's crucial to ensure that Composer is up to date for optimal performance and compatibility. You can update Composer to the latest version by running the following command in your terminal:

```bash
composer self-update
```

Additionally, inconsistencies and issues can sometimes arise from cached data within Composer. Clearing Composer's cache might help resolve any discrepancies you're encountering. To clear the cache, please run:

```bash
composer clearcache
```

After clearing the cache, try running your command again.

If you continue to experience issues or have any further questions, please don't hesitate to get in touch. We're here to help.

Best Regards.

**Comment by chenphp** [comment]
Thank you @bednar  .I tryed and this is what I got
![图片](https://github.com/influxdata/influxdb-client-php/assets/9495197/3c63e9a0-71ee-4c3e-a14a-0fe143d65dc4)
by the way, this is my composer config
![图片](https://github.com/influxdata/influxdb-client-php/assets/9495197/ecc47451-ddfb-47ac-8748-d6f36e24be9c)

**Comment by chenphp** [comment]
Thank you @bednar .My problem has been solved.
