### ISSUE TITLE
Wrong time order

### ISSUE THREAD

**Issue by pemsy** [influxdata/influxdb-client-php#26]
After wuery like this `from(bucket: "parking_app/autogen") |> range(start: -48h ) |> filter(fn: (r) => r._measurement == "device_uplink" and r._field == "rssi")`

query return:

2020-05-07T11:37:09.946Z RSSI2 is -44
2020-05-09T06:37:41.453Z RSSI2 is -71
2020-05-07T11:52:46.025Z RSSI2 is -50
2020-05-08T12:55:02.237Z RSSI2 is -67
2020-05-07T12:55:17.485Z RSSI2 is -47
2020-05-08T14:49:42.114Z RSSI2 is -63
2020-05-08T17:54:50.922Z RSSI2 is -53
2020-05-07T17:54:50.285Z RSSI2 is -49

Its not in a right time order.

Database look like this:
![image](https://user-images.githubusercontent.com/18145949/81471873-8b19e800-91f4-11ea-8d2c-4fd4925aff7d.png)

**Comment by bednar** [comment]
Hi @pemsy,

Could you please provide a more info? Which of your columns are `tags` and which are `fields`. 

The Flux language groups results into tables from same time series.

Regards

**Comment by pemsy** [comment]
its a tags:
![obraz](https://user-images.githubusercontent.com/18145949/81536373-ba069a00-936b-11ea-9c28-d2c87c344667.png)
Its a field:
![obraz](https://user-images.githubusercontent.com/18145949/81536410-ca1e7980-936b-11ea-85d2-2ab90d5ad544.png)

**Comment by bednar** [comment]
The flux aggregate results to tables with same tags. So your query produce more than one table...

You could use [pivot](https://v2.docs.influxdata.com/v2.0/reference/flux/stdlib/built-in/transformations/pivot/) function or [drop](https://v2.docs.influxdata.com/v2.0/reference/flux/stdlib/built-in/transformations/drop/) unwanted tags to produce only one table.

see also:

- https://docs.influxdata.com/flux/v0.65/language/data-model/#table

**Comment by pemsy** [comment]
But when i drop other tag's i receivd this. I drop all other tags.
![image](https://user-images.githubusercontent.com/18145949/81542841-92b4ca80-9375-11ea-81a3-43ca02cad053.png)

**Comment by bednar** [comment]
Ok, so try to use `pivot` that could fits to your requirements.
