### ISSUE TITLE
integrate on codeIgniter 4

### ISSUE THREAD

**Issue by pws2016** [influxdata/influxdb-client-php#40]
Hello, 
i want integrate influxDB on codeIgniter 4 so how i replace 
"require __DIR__ . '/vendor/autoload.php';" with namespace?

**Comment by bednar** [comment]
Hi @pws2016,

did you try `FCPATH`?

- https://codeigniter4.github.io/userguide/general/common_functions.html?highlight=fcpath#FCPATH
- https://codeigniter4.github.io/userguide/general/managing_apps.html#renaming-or-relocating-the-application-directory

Regards
