### ISSUE TITLE
Error on retrieving data!

### ISSUE THREAD

**Issue by pws2016** [influxdata/influxdb-client-php#41]
$query = "from(bucket: \\"{$bucket}"\\) |> range(start: -1h)";
$tables = $client->createQueryApi()->query($query, $org);

this lines return me error:
AH01071: Got error 'PHP message: PHP Parse error: syntax error, unexpected '"\\\\) |> range(start: -1h)"' (T_CONSTANT_ENCAPSED_STRING)

How i fix this?

**Comment by bednar** [comment]
Hi @pws2016,

your query has a wrong escaping:

```php
$query = "from(bucket: \"{$bucket}___"\___) |> range(start: -1h)";
```

the query should looks like:

```php
$query = "from(bucket: \"{$bucket}\") |> range(start: -1h)";
```

Regards
