### ISSUE TITLE
Add support for Guzzle client version 7.x. 

### ISSUE THREAD

**Issue by kanashin** [influxdata/influxdb-client-php#47]
__Proposal:__
 "guzzlehttp/guzzle": "^6.2|^7"

__Current behavior:__
 "guzzlehttp/guzzle": "^6.2"

__Desired behavior:__
Supporting guzzle ^7.0 will allow this library to be used with Laravel 8.

__Alternatives considered:__
.

__Use case:__
Supporting guzzle ^7.0 will allow this library to be used with Laravel 8.

**Comment by bednar** [comment]
I've prepare support for Guzzle 7.x in https://github.com/influxdata/influxdb-client-php/pull/49. Could you take a look?

**Comment by kanashin** [comment]
It works for my project. Thank you.
