### ISSUE TITLE
Self signed SSL certificate

### ISSUE THREAD

**Issue by Shadow505** [influxdata/influxdb-client-php#55]
Hello,

I am using a self signed SSL certificate, unfortunately that results in an exception
Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: self signed certificate

I could not find an option to disable that verification.

**Comment by Shadow505** [comment]
I was able to fix this by adding 

`'verify' => $this->options['verify']`

to the constructor of DefaultApi.php and then adding `'verify' => false` to the options when initializing InfluxDB2\Client. 

Would be good if you add it to the code.

**Comment by bednar** [comment]
@Shadow505 thanks for using our client, We will take a look
