### ISSUE TITLE
SECURITY: Missing support for prepared statements

### ISSUE THREAD

**Issue by ghost** [influxdata/influxdb-client-php#56]
This library must be considered insecure because queries with parameters can only be created by concatenate strings. This is an easy way to introduce security problems through injections

The correct way to do this is to use prepared (like) statements where the query contains placeholders. And the actual parameters are given as key-value store or simple lists. So it is not possible to have incorrectly sanitized parameters which break the query and allow operations not intended by the author

**Comment by bednar** [comment]
Hi @charlemagnelasse,

The InfluxDB API for v2 doesn't supports bind parameters (prepare statement) - see influxdata/influxdb#16109. 

Our API allows to specify `extern` via [Query](https://github.com/influxdata/influxdb-client-php/blob/2c8d18b2ceec0d482517e412deaea61367ea2d69/src/InfluxDB2/Model/Query.php#L273), but working with `extern` is too painful and doesn't offer an alternative for the unsupported bind parameters.

What do you think about sanitazing string something like in JS client: https://github.com/influxdata/influxdb-client-js/blob/master/packages/core/src/query/flux.ts#L40-L99.

- https://docs.influxdata.com/influxdb/v1.8/tools/api/#bind-parameters

Regards
