### ISSUE TITLE
PHP function array_key_last() not available for versions < 7.3

### ISSUE THREAD

**Issue by wnasich** [influxdata/influxdb-client-php#59]
The file composer.json spec v7.1 as minimum versión , however this function used at Worker.php:61 is not available . It could be good maintain 7.1 as minimum and replace the line with below:

`$index = array_keys($data)[count($data)-1];`

https://github.com/influxdata/influxdb-client-php/blob/43e8fa052676fe3554c1011133dc0303dc7e581e/src/InfluxDB2/Worker.php#L61

**Comment by bednar** [comment]
Thanks @wnasich, we will take a look
