### ISSUE TITLE
`InfluxDB2\FluxRecord->getValue()` can spit out a PHP “Undefined Index” Notice

### ISSUE THREAD

**Issue by bramus** [influxdata/influxdb-client-php#64]
__The Problem__

When executing a query that yields no `_value`, calling `getValue()` on a `InfluxDB2\FluxRecord` spits out a PHP Notice:

```
Undefined index: _value in vendor/influxdata/influxdb-client-php/src/InfluxDB2/FluxRecord.php on line 45
```

This should be suppressed, as a returned record might not contain this field 

__Steps to reproduce:__

Execute a Flux query that has a map of drops the column _value or uses a pivot such as [the example one given in the docs](https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/built-in/transformations/pivot/#align-fields-within-each-measurement-that-have-the-same-timestamp)

```
from(bucket:"test")
  |> range(start: 1970-01-01T00:00:00.000000000Z)
  |> pivot(
    rowKey:["_time"],
    columnKey: ["_field"],
    valueColumn: "_value"
  )
```

Executing the above query and calling `getValue()` on each record of the stream will give a notice

```php
$this->client = new Client([…]);
$this->queryApi = $this->client->createQueryApi();
$this->influxParser = $influxQueryApi->queryStream($fluxQuery);

foreach ($this->influxParser->each() as /* \InfluxDB2\FluxRecord */ $record) {
  echo $record->getValue();
}
```

__Expected behavior:__

No PHP Notice to be shown on screen.

__Actual behavior:__

A PHP Notice is shown on screen.

__Specifications:__

 - Client Version: all _(tested with 1.15.2)_
 - InfluxDB Version: all
 - Platform: all

**Comment by bednar** [comment]
Hi @bramus,

thanks for using our client.

I think the hiding of exceptions as a default behaviour is bad practise and it could be more confusing. Without notice you don't know that your code is invalid (pivoted data doesn't have the `_value` column). If you want to hide notice for `getValue` you could use `@$record->getValue()`.

Anyway I will improve docs for `FluxRecord` to clarify how it works.

Regards

**Comment by bramus** [comment]
Don't think using `@` is considered a best practice. As a library author myself, I think it's the library that should harden itself against wrong usage and leaking sensitive information.

I see some options to solve this here:
- Return `null` in case no `_value` is stored on the `fields` array. With the null coalescing operator this is a one-line change.
- Throw an Exception with a nice descriptive error message.

One of these would form a nice solution I think.

**Comment by bednar** [comment]
@bramus thanks for response

> Don't think using @ is considered a best practice. 

Agree

> Throw an Exception with a nice descriptive error message.

From my point of view this is a better option.

**Comment by bramus** [comment]
Great, we're on the same page here :)

**Comment by bednar** [comment]
@bramus, I've prepare the PR - #65. Do you have time to quick review?

**Comment by bramus** [comment]
Looks good from here. Added one language remark.
