### ISSUE TITLE
Code 500 Influx CLient on VPS

### ISSUE THREAD

**Issue by GerritRie** [influxdata/influxdb-client-php#70]
Hello guys i have a problem using the PHP_Client.
On my Xampp Local Machine (Windows 10) everthing works great. But if i put the exact same files on my Linux VPS the Server gives me a 500 Code:

Can someone maybe help me ?

Here ist my Code:

```
<?php

require __DIR__ . '\..\vendor\autoload.php';


use InfluxDB2\Client;
use InfluxDB2\Model\WritePrecision;
use InfluxDB2\Point;
echo getdata("Jürgen ", "M_AC_Power");
function getdata($kunde,$wert)
{
# You can generate a Token from the "Tokens Tab" in the UI
    $token = '';
    $org = 'JH';
    $bucket = 'PV-Daten';
    $client = new Client([
        "url" => "http://95.111.224.215:8086",
        "token" => $token,
    ]);


    $query = '

from(bucket: "PV-Daten")
  |> range(start: -5s)
  |> filter(fn: (r) => r["name"] == "'.$kunde.'")
  |> filter(fn: (r) => r["_field"] == "'.$wert.'")
  |> last()

  ';

    $tables = $client->createQueryApi()->query($query, $org);


    if (isset($tables[0])) {
        $data = ($tables[0]);
        $data = $data->records;
        $data = ($data[0]);

        return ($data->getValue());
    } else {
        return ("fail");
    }

}
```

**Comment by bednar** [comment]
@GerritRie, thanks for using our client. Could you please share a debug output from client? We need more info to be able to help you. You could enable debug by:

```php
$client = new Client([
    "url" => "http://95.111.224.215:8086",
    "token" => $token,
    "debug" => true
]);
```

**Comment by GerritRie** [comment]
Yes i added the Debug Tag. But im not even abel to open the PHP. 

`Failed to load resource: the server responded with a status of 500 (Internal Server Error)`


Beginn of PHP:
```
<?php
require __DIR__ . '\..\vendor\autoload.php';
use InfluxDB2\Client;
use InfluxDB2\Model\WritePrecision;
use InfluxDB2\Point;
```

**Internal:**
<a href="https://ibb.co/rQqRWHF"><img src="https://i.ibb.co/0n1Rwrm/Unbenannt.png" alt="Unbenannt" border="0"></a>

**Website:**
<a href="https://ibb.co/Cznfkdc"><img src="https://i.ibb.co/wRKf9Hk/Unbenannt.png" alt="Unbenannt" border="0"></a>

**Comment by bednar** [comment]
> Failed to load resource: the server responded with a status of 500 (Internal Server Error)

Try to checkout the `log` of InfluxDB server.

**Comment by GerritRie** [comment]
There is nothing in it i think there is something wrong with the Includements. But i cant Figure out wat i do wrong

**Comment by bednar** [comment]
You could try `$client->health();` to check your connection and includes.

https://github.com/influxdata/influxdb-client-php/blob/master/README.md#check-the-server-status

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
