### ISSUE TITLE
Unpublish version 12.0

### ISSUE THREAD

**Issue by stayallive** [influxdata/influxdb-client-php#75]
Hi there,

It looks like 12.0 was released together with 1.12.0, which I assume 12.0 was a mistake since the tag is already gone.

But the version is still published on Packagist which makes updating a bad plan since I 12.0 will always be newer than any actual new version.

> https://packagist.org/packages/influxdata/influxdb-client-php

So I would recommend to remove 12.0 from Packagist.

**Comment by bednar** [comment]
> Hi there,
> 
> It looks like 12.0 was released together with 1.12.0, which I assume 12.0 was a mistake since the tag is already gone.

Yes, it was mistake.

> But the version is still published on Packagist which makes updating a bad plan since I 12.0 will always be newer than any actual new version.
> 
> > https://packagist.org/packages/influxdata/influxdb-client-php
> 
> So I would recommend to remove 12.0 from Packagist.

I will take a look... stay tuned.

**Comment by bednar** [comment]
The `12.0` is removed from Packagist. Thanks again for issue

**Comment by stayallive** [comment]
Thanks for the quick response! Much appreciated.
