### ISSUE TITLE
Add method to retrieve column from table

### ISSUE THREAD

**Issue by paul121** [influxdata/influxdb-client-php#85]
__Proposal:__
Add a method to the [`InfluxTable`](https://github.com/influxdata/influxdb-client-php/blob/master/src/InfluxDB2/FluxTable.php) object to return a column with a specified label, eg: `$table->getColumn(string $column_label)`

__Current behavior:__
Currently the table columns are available in a simple array and getting a specific column requires a manual search through the array.

__Desired behavior:__
Make it easier to find a column of a specific label! This search logic could be encapsulated in a simple helper method on the `InfluxTable` class. The method would return `InfluxColumn|None`.

__Alternatives considered:__
Designing a reusable helper method myself. But it seems sensible to include this in the `InfluxTable` class if it would be useful for others.

This is my current implementation to pull out the `defaultValue` of the `result` column from an `InfluxTable`:

```php
  // Execute query.
  /** @var \InfluxDB2\FluxTable[] $result */
  $result = $query_api->query($final_query);

  // Collect all the data.
  $all_data = [];
  foreach ($result as $table) {

    // *** Column search right here! ****
    $result_key = array_search('result', array_column($table->columns, 'label'));
    $name = $table->columns[$result_key]->defaultValue;

    foreach ($table->records as $record) {
      $datetime = new \DateTime($record->getTime());
      $formatted = $datetime->format('n/j');
      $all_data[$name][$formatted][$record->getField()] = $record->getValue();
    }
  }
```

__Use case:__
My Flux query returns two tables, each identified with a different name via `yield(name: "table_name")`. When parsing the result of this query I need to know the table name which is stored in the table's `result` column.

Would you be open to adding methods to the `InfluxTable` class? I noticed that the PHP implementation is identical to the Python implementation of the [`InfluxTable`](https://github.com/influxdata/influxdb-client-python/blob/master/influxdb_client/client/flux_table.py), and am unsure if these all need to be kept in sync. I hope that is not the case, but alas. It's my understanding that the API services are auto-generated from the openapi spec, but these other classes are not?

Alternatively, perhaps there is a better way to accomplish what I am trying to do, in which case I would love to hear any suggestions :-)

**Comment by bednar** [comment]
Hi @paul121,

thanks for using our client.

> Would you be open to adding methods to the `InfluxTable` class? 

Yes, definitely. Every PR is welcome so feel to free to create PR with your requested method.

> I noticed that the PHP implementation is identical to the Python implementation of the [`InfluxTable`](https://github.com/influxdata/influxdb-client-python/blob/master/influxdb_client/client/flux_table.py), and am unsure if these all need to be kept in sync. I hope that is not the case, but alas. It's my understanding that the API services are auto-generated from the openapi spec, but these other classes are not?

Yes, only classes from `Model/*.php` and `Service/*.php` are autogenerated.

Regards

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
