### ISSUE TITLE
Wrong documentation for deleting data

### ISSUE THREAD

**Issue by logarytm** [influxdata/influxdb-client-php#87]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Run the code from `DeleteDataExample.php`

__Expected behavior:__
Data is deleted.

__Actual behavior:__
`DefaultService` doesn't have a `deletePost` method.

__Specifications:__
 - Client Version: 2.1.0
 - InfluxDB Version: OSS 2.x (shouldn't be relevant though)
 - Platform: PHP 7.4

I've ended up using `DeleteService::postDelete()`, but that presented another problem which I'm going to report in a new issue (you have to pass the org and bucket names to the method, otherwise you get a 400 Bad Request that org/orgID/bucket/bucketID are missing).

Edit: Apparently the `deletePost()` method has disappeared in `2.0.0`.

**Comment by bednar** [comment]
Hi @logarytm,

thanks for using our client.

I have prepared a fixed version within #89. If you would like to see fixed version you can switch to branch [fix/delete-example](https://github.com/influxdata/influxdb-client-php/tree/fix/delete-example).

Regards
